import React from "react";
import Head from "next/head";
import Profil from "../engine/component/Profil/Profil";
import Projet from "../engine/component/Projet/Projet";
import Skills from "../engine/component/Skills/Skills";
import { GlobalStyle } from "../engine/styled/global";

export default function Home() {
  return (
    <section>
      <Head>
        <title>Portfolio Parodi Raphaël</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyle />
      <div className="wrapper_inside">
        <Profil></Profil>
        <Skills></Skills>
        <Projet></Projet>
      </div>
    </section>
  );
}
