import React from "react";
import Head from "next/head";
import Profil from "../engine/component/Profil/Profil";
import Projet from "../engine/component/Projet/Projet";
import Skills from "../engine/component/Skills/Skills";
import { GlobalStyle } from "../engine/styled/global";
import ArchitecturalContainer from "../engine/component/ArchitectureContainer/ArchitectureContainer";
import {
  HtmlParams_footer,
  HtmlParams_hero,
  HtmlParams_projet,
  HtmlParams_skills,
  HtmlParams_softSkills,
} from "./index_css";
import SoftSkills from "../engine/component/SoftSkills/SoftSkills";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio Parodi Raphaël</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GlobalStyle />
      <ArchitecturalContainer {...HtmlParams_hero}>
        <Profil></Profil>
      </ArchitecturalContainer>
      <ArchitecturalContainer {...HtmlParams_skills}>
        <Skills></Skills>
      </ArchitecturalContainer>
      <ArchitecturalContainer {...HtmlParams_projet}>
        <Projet></Projet>
      </ArchitecturalContainer>
      <ArchitecturalContainer {...HtmlParams_softSkills}>
        <SoftSkills></SoftSkills>
      </ArchitecturalContainer>
    </>
  );
}
